version: '3.1'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
  nana-mongo-app:
    image: mhussain78/nana-mongo-app:0.0.3
    ports:
      - 8088:8080
    environment:
      SPRING_DATA_MONGODB_URI: "mongodb://admin:password@mongodb:27017/user-account?authSource=admin"

volumes:
  mongo-data:
    driver: local